name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [main]
  pull_request:

env:
  PACKAGE_NAME: GWAI
  PYTHON_VERSION: "3.8"

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Run `ruff check` stable ecosystem check
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - run: pip install ruff
      - run: ruff check ./ --config pyproject.toml
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."


